import type { Ui } from "../types";

export const ui: Ui = {
  a11y: {
    menu: "Open menu",
    language: "Site language",
    close: "Close",
    agents: "AI agents",
  },
  palette: {
    label: "Color palette",
    names: {
      ember: "Ember",
      paper: "Paper",
      cobalt: "Cobalt",
      crimson: "Crimson",
      solar: "Solar",
      monochrome: "Monochrome",
    },
  },
  pricing: { recommended: "recommended" },
  pains: { seeResult: "See automated result", hideResult: "Hide result" },
  form: {
    failed: "Couldn't send the request. Please try again.",
    notConnected: "The form isn't connected. Please write to us directly.",
  },
  booking: {
    date: "Date",
    time: "Time",
    name: "Name",
    email: "Email",
    phone: "Phone (optional)",
    note: "What should we cover on the call? (optional)",
    sending: "Sending…",
    failed: "Something went wrong.",
  },
  portal: {
    account: "account",
    bonuses: "bonuses",
    lastVisit: "last sign-in",
    logout: "Sign out",
    tabLogin: "Sign in",
    tabSignup: "Sign up",
    password: "Password",
    passwordHint: "Password (at least 8 characters)",
    phone: "Phone (optional)",
    submitLogin: "Sign in",
    submitSignup: "Create account",
    failed: "Something went wrong.",
    emailTaken: "An account with that email already exists.",
    badCredentials: "Invalid email or password.",
  },
  admin: {
    loading: "Loading…",
    title: "Admin",
    user: "Login (email)",
    pass: "Password",
    signIn: "Sign in",
    badCredentials: "Invalid credentials.",
    dashboard: "Dashboard",
    signOut: "Sign out",
    empty: "—",
    leads: {
      heading: "website leads",
      cols: ["When", "Name", "Contact", "Task", "Source"],
      empty: "No leads yet.",
    },
    bookings: {
      heading: "bookings",
      cols: ["When", "Who", "Contact", "Note", "Status", ""],
      empty: "No bookings yet.",
      confirm: "confirm",
      cancel: "cancel",
      status: { pending: "pending", confirmed: "confirmed", cancelled: "cancelled" },
    },
    customers: {
      heading: "clients",
      cols: ["Email", "Phone", "Bonuses", "Last sign-in"],
      empty: "No clients yet.",
    },
  },
  emails: {
    fields: {
      when: "When",
      name: "Name",
      email: "Email",
      phone: "Phone",
      note: "Note",
      contact: "Contact",
      task: "Task",
      source: "Source",
    },
    bookingCustomer: {
      subject: "Call request received — {brand}",
      title: "Thank you, {name}!",
      intro: "We've received your call request and will confirm it by email shortly.",
      footer: "If you didn't request a call, simply ignore this email.",
    },
    bookingAdmin: {
      subject: "New call request: {name} — {date} {time}",
      title: "New call request",
      intro: "A new request came in. Open the admin panel to confirm or cancel it.",
      footer: "Sent automatically from the {brand} website.",
    },
    bookingConfirmed: {
      subject: "Call confirmed — {brand}",
      title: "Call confirmed",
      intro: "Your call is confirmed — the meeting link will arrive in a separate email. Talk soon!",
      footer: "Need to reschedule? Just reply to this email.",
    },
    leadAdmin: {
      subject: "New lead from the website: {name}",
      title: "New lead from the website",
      intro: "Someone filled in the form in the contact block. Reach out while the lead is hot.",
      footer: "Sent automatically from the {brand} website.",
    },
  },
};
